# Generated by Django 5.2.4 on 2025-07-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0003_genre_active_genre_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
