# Generated by Django 5.2.4 on 2025-07-29 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0004_alter_genre_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
