# Generated by Django 5.2.4 on 2025-08-07 21:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0002_alter_movie_options_remove_movie_genres_movie_genres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stars', models.IntegerField(choices=[(0, 'O estrelas'), (1, '1 estrela'), (2, '2 estrelas'), (3, '3 estrelas'), (4, '4 estrelas'), (5, '5 estrelas')], validators=[django.core.validators.MinValueValidator(0, 'Mínino 0'), django.core.validators.MaxValueValidator(5, 'Máximo 5')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movie_reviews', to='movies.movie')),
            ],
            options={
                'verbose_name_plural': 'Reviews',
                'ordering': ['movie__title'],
            },
        ),
    ]
