# Generated by Django 5.2.4 on 2025-08-04 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('acronym', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Nationalities',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='actor',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name_plural': 'Actors'},
        ),
        migrations.RemoveField(
            model_name='actor',
            name='age',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='gender',
        ),
        migrations.AddField(
            model_name='actor',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actor',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actors_nationality', to='actors.nationality'),
        ),
    ]
