# Generated by Django 5.2.4 on 2025-08-05 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0002_nationality_alter_actor_options_remove_actor_age_and_more'),
        ('genres', '0006_alter_genre_options_alter_genre_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('resume', models.TextField(blank=True, null=True)),
                ('genres', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movie_genres', to='genres.genre')),
                ('movie_cast', models.ManyToManyField(related_name='movie_cast', to='actors.actor')),
            ],
        ),
    ]
